### ISSUE TITLE
Request to revert the change of preventing natures prophet sprouting

### ISSUE THREAD

**Issue by mo-han** [arcadia-redux/12v12#98]
1. It's too buggy now, NP is not only preventing from sprouting on allied heroes, but also enemy heroes, and allied creeps. This change currently crippled NP, as sprout is a very import skill against enemies.

2. Sprout is not just an abusing skill for allies, it can be used to save allies, though I agree that kind of scenario is rare, but it's very useful when needed, but this change just totally eliminated this usage.

3. You can't just cut your hands simply because them might do some bad things. Game balancing or anti-trolling is not achieved in this way, which is lame.

4. Anyway fix the severe bugs first.

**Comment by darklordabc** [comment]
1. We will try to fix the bugs asap.

2. The pros of allowing it is outweighed by the cons. I don't think I've ever seen a Nature's prophet cast sprouts on allies to save them, its extremely rare, but its a very easy way to troll, so by that calculation I think its better nerfed.

3. We disable some functionality if we think the reward is worth it. This is one of those cases IMO.

4. Do you know of any severe bugs?

**Comment by mo-han** [comment]
Great, thanks.
As long as you can fix the issue that NP not able to sprout on enemies, other things could be put aside.

**Comment by mo-han** [comment]
@darklordabc 
Hi, is this issue fixed yet? Though most of the time sprouting on enemies are normal, there is still a chance large enough that it will fail, and when such happens, the conditions and the situation vary randomly. Sometimes sprout failed only once then, I could cast it again right away and succeeded. Sometimes it failed continuously in a short time, I could only helplessly keep casting it with no success and watched the enemy ran away, however, just several seconds later, I could again cast it on enemy successfully. Similar situations happened when I tried to use Ctrl + Q to learn or upgrade the sprout skill: sometimes succeeded, sometimes failed. The issue has been fixed partly, but it's still not completely solved.

**Comment by linovifian** [comment]
Can confirm that it still doesn't work, played a game today with NP and was unable to sprout an enemy, which has disabled help.

Though I can also confirm that it later worked again on the same enemy. I am not sure if they enabled help in the meantime or not.

Maybe it's something early game? E.g. in the first minutes, because later on in the game it worked like intended

**Comment by darklordabc** [comment]
@Sheodar can you look at the NP sprout anti-troll code and see why this buggy behaviour is happening.

**Comment by darklordabc** [comment]
@mo-han is this fixed?
